/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author Axel
 */
public class Functions extends javax.swing.JFrame {

    /**
     * Creates new form Functions
     */
    public Functions() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        registerButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        datesButtons = new javax.swing.JButton();
        editInformationButton = new javax.swing.JButton();
        medicalHistoryButton1 = new javax.swing.JButton();
        editInformationButton1 = new javax.swing.JButton();
        editInformationButton2 = new javax.swing.JButton();
        datesButtons1 = new javax.swing.JButton();
        datesButtons2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        registerButton.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        registerButton.setText("Registrar Paciente");
        registerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        backButton.setText("←");
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel1.setText("Funciones");

        datesButtons.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        datesButtons.setText("Registrar Citas");
        datesButtons.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        datesButtons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datesButtonsActionPerformed(evt);
            }
        });

        editInformationButton.setFont(new java.awt.Font("Roboto", 0, 23)); // NOI18N
        editInformationButton.setText("Editar Información");
        editInformationButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editInformationButton.setFocusable(false);
        editInformationButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editInformationButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        editInformationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editInformationButtonActionPerformed(evt);
            }
        });

        medicalHistoryButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        medicalHistoryButton1.setText("Mostrar Citas");
        medicalHistoryButton1.setToolTipText("");
        medicalHistoryButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        medicalHistoryButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicalHistoryButton1ActionPerformed(evt);
            }
        });

        editInformationButton1.setFont(new java.awt.Font("Roboto", 0, 23)); // NOI18N
        editInformationButton1.setText("Eliminar Paciente");
        editInformationButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editInformationButton1.setFocusable(false);
        editInformationButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editInformationButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        editInformationButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editInformationButton1ActionPerformed(evt);
            }
        });

        editInformationButton2.setFont(new java.awt.Font("Roboto", 0, 23)); // NOI18N
        editInformationButton2.setText("Mostrar Pacientes");
        editInformationButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editInformationButton2.setFocusable(false);
        editInformationButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editInformationButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        editInformationButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editInformationButton2ActionPerformed(evt);
            }
        });

        datesButtons1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        datesButtons1.setText("Impresiones Cita");
        datesButtons1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        datesButtons1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datesButtons1ActionPerformed(evt);
            }
        });

        datesButtons2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        datesButtons2.setText("Datos Clínicos");
        datesButtons2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        datesButtons2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datesButtons2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addGap(216, 216, 216)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 83, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registerButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editInformationButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datesButtons, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datesButtons1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(medicalHistoryButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editInformationButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editInformationButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datesButtons2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backButton)
                    .addComponent(jLabel1))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editInformationButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(editInformationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editInformationButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datesButtons, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(medicalHistoryButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datesButtons1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datesButtons2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        this.setVisible(false);
        Register_Pacient Registrar = new Register_Pacient();
        Registrar.setVisible(true);
    }//GEN-LAST:event_registerButtonActionPerformed

    private void editInformationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editInformationButtonActionPerformed
        this.setVisible(false);
        Search_Pacient Search = new Search_Pacient("Editar");
        Search.setVisible(true);
    }//GEN-LAST:event_editInformationButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        Login Login = new Login();
        Login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void datesButtonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datesButtonsActionPerformed
        this.setVisible(false);
        Dates_Register Dates = new Dates_Register();
        Dates.setVisible(true);
    }//GEN-LAST:event_datesButtonsActionPerformed

    private void medicalHistoryButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicalHistoryButton1ActionPerformed
        this.setVisible(false);
        Programed_Dates Prog = new Programed_Dates();
        Prog.setVisible(true);
    }//GEN-LAST:event_medicalHistoryButton1ActionPerformed

    private void editInformationButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editInformationButton1ActionPerformed
        this.setVisible(false);
        Search_Pacient Search = new Search_Pacient("Eliminar");
        Search.setVisible(true);
    }//GEN-LAST:event_editInformationButton1ActionPerformed

    private void editInformationButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editInformationButton2ActionPerformed
        this.setVisible(false);
        List_Patients List = new List_Patients();
        List.setVisible(true);
    }//GEN-LAST:event_editInformationButton2ActionPerformed

    private void datesButtons1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datesButtons1ActionPerformed
        this.setVisible(false);
        Search_Date Search = new Search_Date();
        Search.setVisible(true);
    }//GEN-LAST:event_datesButtons1ActionPerformed

    private void datesButtons2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datesButtons2ActionPerformed
        this.setVisible(false);
        Clinical_Data Cli = new Clinical_Data();
        Cli.setVisible(true);
    }//GEN-LAST:event_datesButtons2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Functions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Functions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Functions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Functions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Functions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton datesButtons;
    private javax.swing.JButton datesButtons1;
    private javax.swing.JButton datesButtons2;
    private javax.swing.JButton editInformationButton;
    private javax.swing.JButton editInformationButton1;
    private javax.swing.JButton editInformationButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton medicalHistoryButton1;
    private javax.swing.JButton registerButton;
    // End of variables declaration//GEN-END:variables
}
